{% set name = "libertem-blobfinder" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libertem-blobfinder-{{ version }}.tar.gz
  sha256: 21805571212fe3f63cb0aa10ec97e98b7613e2d9a43dcdb69b4a6e5bc46aa755

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numba >=0.49
    - numpy
    - python >=3.6
    - libertem >= 0.5.0
    - scikit-image
    - matplotlib

test:
  imports:
    - libertem_blobfinder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://libertem.github.io/LiberTEM-blobfinder
  summary: LiberTEM correlation and refinement library
  license: GPL-3.0
  license_file: LICENSE
  description: |
    LiberTEM-blobfinder is a package for correlation-based peak finding
    and strain mapping. It is part of the LiberTEM project.
  doc_url: https://libertem.github.io/LiberTEM-blobfinder/
  dev_url: https://github.com/LiberTEM/LiberTEM-blobfinder

extra:
  recipe-maintainers:
    - sk1p
    - uellue
    - matbryan52
